### ISSUE TITLE
Jarvis restarts when properly exited and not way to see Jarvis output

### ISSUE THREAD

**Issue by alexylem** [Oliv4945/jarvis-systemd-startup#1]
Today I installed your plugin to test it deeply, but I see several issues:
1. When I quit Jarvis normally (to install plugins, change settings...), it restarts immediately
I tried to change `Restart=always` to `Restart=on-failure` but did not work. Though I do exit Jarvis properly with a clean exit code...
2. The output is not sent to the logs and showing Jarvis output (menu option when starting Jarvis) does not show them.
This is because you start Jarvis with `-n` instead of `-b`. I tried changed with `-b` but it's not starting...

I would like to help because this plugin is great, but for now I have no solution. I continue investigating...

**Comment by Oliv4945** [comment]
> I tried to change Restart=always to Restart=on-failure but did not work.

Yes, I already spotted that and did not had time to change it. But it should work, I'll focus on that soon

> This is because you start Jarvis with -n instead of -b. I tried changed with -b but it's not starting...

Ok, did not knew it, but I will check in the same time.

**Comment by Oliv4945** [comment]
Ok...Hard one :-)

First the background mode: What is the aim to start Jarvis in background mode from systemd ? Because with `-b` option systemd understands that Jarvis stopped just after `You can now close this terminal`...and never monitor it again :/

Now what happens with `-n` : 
1. Jarvis is started by systemd
2. With `jarvis.sh -q` we ask Jarvis to exit (code 0)
3. systemd detects the exit, then triggers `ExecStop`.
4. Jarvis.sh is already stopped so `ExecStop` returns code 1
5. systemd does not likes code 1, so restart Jarvis...

So we should use `RemainAfterExit=true` to prevent triggering `ExecStop`, which mean that we have to user `service jarvis restart` to start Jarvis again.

Nevertheless you can not just use `-b` without the option `RemainAfterExit=true` too, because systemd triggers `ExecStop` when Jarvis exits, so stop Jarvis...

I pushed a fix, you have to uninstall/install the plugin to have it

**Comment by alexylem** [comment]
Great, I'll try this! Thanks a lot!

**Comment by alexylem** [comment]
>I pushed a fix, you have to uninstall/install the plugin to have it

Menu Plugins > Installed > Systemd > Reinstall is just made for this 👍  (and it worked, I have the new `jarvis.service`)
![image](https://cloud.githubusercontent.com/assets/11017174/25633848/cbc85f76-2f78-11e7-907e-c6dd771c63a1.png)

**Comment by alexylem** [comment]
It works, thanks.
For the background mode you have a point.
I tried with `-b` it works (I have the output display) but you are right it's pointless as we loose the monitoring.
Here is what I propose to have the output display back:
```
ExecStart=/home/pi/jarvis/jarvis.sh -n 2&1 >> /home/pi/jarvis/jarvis.log
```
Or even better with the timestamps to match [jv_start_in_background](https://github.com/alexylem/jarvis/blob/master/utils/utils.sh#L315) function
```
ExecStart=/home/pi/jarvis/jarvis.sh -n 2&1 | awk '{ print strftime("%Y-%m-%d %H:%M:%S"), $0; fflush(); }' >> /home/pi/jarvis/jarvis.log
```
I can propose a PR on your plugin if you are ok with this approach.

**Comment by Oliv4945** [comment]
>Here is what I propose to have the output display back:

Hi @alexylem, I don't really understand what are you trying to do ?
1. We can still connect to Jarvis thanks to `./jarvis.sh`=>then show output
2. Previous outputs are stored in journalctl, you can access them thanks to `sudo journalctl -u jarvis.service`

If it is enough for you I will update the documentation to reflect that, if not please submit your PR :-)


>Menu Plugins > Installed > Systemd > Reinstall is just made for this :+1: (and it worked, I have the new jarvis.service)

Ok, I did not notice it.

**Comment by alexylem** [comment]
>Previous outputs are stored in journalctl, you can access them thanks to sudo journalctl -u jarvis.service

Aaaah this is the piece of the puzzle I was missing. It's good to have it documented in your README.md. If people complain they don't see the output using:
```shell
sudo systemctl start jarvis
./jarvis.sh
# select Show Output from menu
```
![image](https://cloud.githubusercontent.com/assets/11017174/25675364/7c755e30-303e-11e7-9a9f-871aac8c5d29.png)
Then I'll see how this can be improved.

**Comment by Oliv4945** [comment]
Ok, done in 5d967d62b0c04d9c089b0345f9fd5a209bda9efb.
If it fit your needs please close the issue :-)

**Comment by alexylem** [comment]
After #4 we can close
